// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM4CqABxjYMGmsf0SBUgUlA33tVfwtSCY',
    appId: '1:612509306796:web:b4c31d55264b3a5936f409',
    messagingSenderId: '612509306796',
    projectId: 'anks-project-test',
    authDomain: 'anks-project-test.firebaseapp.com',
    storageBucket: 'anks-project-test.appspot.com',
    measurementId: 'G-BME9RB9VPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCinNJiW4reaRCX1hnIqZ-zX00BgD13L4s',
    appId: '1:612509306796:android:ddddf09e5e2ea51636f409',
    messagingSenderId: '612509306796',
    projectId: 'anks-project-test',
    storageBucket: 'anks-project-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfmRqYNp6tMayUOOTEU75Ovzz7kx9YVzc',
    appId: '1:612509306796:ios:f9bf88f7e042b6cc36f409',
    messagingSenderId: '612509306796',
    projectId: 'anks-project-test',
    storageBucket: 'anks-project-test.appspot.com',
    iosClientId: '612509306796-dvn5k6vll5bc0ndfmiu5qmhknut52o2j.apps.googleusercontent.com',
    iosBundleId: 'in.test.ankithsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfmRqYNp6tMayUOOTEU75Ovzz7kx9YVzc',
    appId: '1:612509306796:ios:f9bf88f7e042b6cc36f409',
    messagingSenderId: '612509306796',
    projectId: 'anks-project-test',
    storageBucket: 'anks-project-test.appspot.com',
    iosClientId: '612509306796-dvn5k6vll5bc0ndfmiu5qmhknut52o2j.apps.googleusercontent.com',
    iosBundleId: 'in.test.ankithsapp',
  );
}
